Update .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -22,11 +22,6 @@ matrix:
       language: java
       osx_image: xcode9.2
       install: true
-      
-before_install:
-  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
-  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install freetype; brew install ccache; fi
-  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi
 
 cache:
   ccache: true
@@ -38,6 +33,23 @@ cache:
 env:
   global:
     - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then PATH=/usr/lib/ccache:${PATH}; fi
+    - TIMEOUT=0
+    
+before_install:
+  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
+  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install freetype; brew install ccache; fi
+  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi
+# setup timeout
+- |
+  if [ $TRAVIS_OS_NAME == 'osx' ]; then
+    # Try to workaround travis-ci/travis-ci#6410 by
+    # introducing a timeout fulction, which will timeout before the builder,
+    # returning a 'fake' success (eg. 0), tricking it to store the cache.
+    TIMEOUT=60
+  fi
+
+  # Implement a platform-independent timeout function.
+  function timeout() { perl -e 'alarm shift; exec @ARGV' "$@"; }
   
 script: 
     - export OUR_DIR=$(pwd)
@@ -48,9 +60,10 @@ script:
     - mkdir -p build && mkdir -p installation && cd build
     - export OCE_INSTALL_DIR=$(pwd)/../installation/lib/oce-0.18/
     - cmake .. -DLLVM_CCACHE_BUILD=ON -DCMAKE_BUILD_TYPE=Release -DOCE_BUILD_SHARED_LIB=OFF -DOCE_USE_TCL_TEST_FRAMEWORK=OFF -DOCE_TESTING=OFF -DOCE_DRAW=OFF -DOCE_VISUALISATION=ON -DOCE_OCAF=ON -DOCE_DATAEXCHANGE=ON -DOCE_COPY_HEADERS_BUILD=ON -DOCE_MULTITHREAD_LIBRARY=OPENMP -DOCE_INSTALL_PREFIX="$(pwd)/../installation" 
-    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then (timeout 60 make -j4 || true) ; fi
-    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make -j8; fi
-    - make install
+    - | timeout $TIMEOUT make -j4
+        timeout $TIMEOUT make install
+        # Convert the timeout exit code to 0.
+        RESULT=$?; if [ $RESULT -eq 0 ] || [ $RESULT -eq 142 ]; then true; else false; fi;
     - cd $OUR_DIR
     - mkdir -p build && cd build
     - cmake .. -DOCE_DIR=$OCE_INSTALL_DIR || true
